version: '3.8'

services:
  postgres:
    image: docker.io/postgres:17-alpine
    environment:
      POSTGRES_DB: chatroom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=chatroom
      - JWT_SECRET=your-secret-key
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    environment:
      - REACT_APP_API_URL=http://backend:8080
      - REACT_APP_WS_URL=ws://backend:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: 